### ISSUE TITLE
Cannot use username with "." and "@" together

### ISSUE THREAD

**Issue by DeLoWaN** [hryamzik/redmine_mention_plugin#10]
Hello,

Usernames with "." or "@" works correctly, like `foo.bar`, or `foo@bar`. But I use emails as username, like `foo.bar@foo.bar`. I this case, the user gets mentionned, but the replacement string on the resulting issue is messed up and does not show the link to the user profile.

Thanks

**Comment by hryamzik** [comment]
Hi @kalumkalac, PRs are welcomed. Note that there're test cases [here](https://github.com/hryamzik/redmine_mention_plugin/blob/dev/test/unit/content_replace_test.rb).

**Comment by DeLoWaN** [comment]
Hello @hryamzik, I tried playing with the regex this morning, but I cannot get it to work. I'm no Ruby developer (I'm a sysadmin actually) and don't know how to develop a plugin on Redmine, that's why I prefer asking to someone with experience.

**Comment by DeLoWaN** [comment]
Well nevermind it's a [bug](http://www.redmine.org/issues/26443) in Redmine itself, I was on 3.4.2.

**Comment by hryamzik** [comment]
>  I tried playing with the regex this morning, but I cannot get it to work. I'm no Ruby developer (I'm a sysadmin actually) and don't know how to develop a plugin on Redmine

That's probably the best definition of the difference between sysadmin and devops I've seen in a while.
